name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build rust
      run: |
        wasm-pack build --out-dir ../react/sigma --release
      working-directory: ./sigma

    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Build react
      run: |
        npm install
        npx webpack
      working-directory: ./react
